import { Event, StaffMember } from "./types";

export const defaultDepartments = [
  "Behandelingkamer1",
  "Management",
  "Bijzonderheden-Verlof-Cursus-...",
  "Financien",
];

export const defaultEvents: Event[] = [
  {
    id: "1",
    department: "HG",
    title: "Surgery",
    startTime: "11:00",
    endTime: "13:00",
    staff: "Haico de Gast",
    color: "orange",
    column: 0,
    subColumn: 0,
    subColumnSpan: 1,
    date: "2026-02-04",
    description: "Scheduled surgery procedure in operating room",
  },
  {
    id: "2",
    department: "DL",
    title: "Pijnspecialist",
    startTime: "11:00",
    endTime: "13:30",
    staff: "Diane Lane",
    color: "green",
    column: 0,
    subColumn: 1,
    subColumnSpan: 1,
    date: "2026-02-04",
    description: "Pain specialist consultation",
  },
  {
    id: "3",
    department: "HG",
    title: "Pijnspecialist",
    startTime: "13:00",
    endTime: "15:00",
    staff: "Diane Lane",
    color: "yellow",
    column: 0,
    columnSpan: 2,
    subColumn: 2,
    subColumnSpan: 3,
    date: "2026-02-04",
    description: "Extended pain management session",
  },
  {
    id: "4",
    department: "HG",
    title: "Pijnspecialist",
    startTime: "11:30",
    endTime: "13:30",
    staff: "Haico de Gast",
    color: "orange",
    column: 1,
    columnSpan: 2,
    subColumn: 2,
    subColumnSpan: 3,
    date: "2026-02-04",
    description: "Pain specialist follow-up appointment",
  },
  {
    id: "5",
    department: "HG",
    title: "Pijnspecialist",
    startTime: "11:00",
    endTime: "15:30",
    staff: "Diane Lane",
    color: "green",
    column: 2,
    columnSpan: 2,
    subColumn: 2,
    subColumnSpan: 2,
    date: "2026-02-04",
    description: "Late afternoon pain management clinic",
  },
  {
    id: "6",
    department: "HG",
    title: "Pijnspecialist",
    startTime: "11:00",
    endTime: "13:00",
    staff: "Diane Lane",
    color: "yellow",
    column: 3,
    subColumn: 1,
    subColumnSpan: 1,
    date: "2026-02-04",
    description: "Pain specialist consultation",
  },
];

export const defaultStaff: StaffMember[] = [
  {
    id: "1",
    initials: "EO",
    name: "Elijah Oyin",
    totalHours: "1158.0hrs",
    overtimeHours: "38.0hrs",
    dateRange: "Jan 8 - Jan 15",
    daysWorked: ["m", "di", "w", "do", "vr"],
    status: "onLeave",
  },
  {
    id: "2",
    initials: "DL",
    name: "Diane Lane",
    totalHours: "1158.0hrs",
    overtimeHours: "38.0hrs",
    dateRange: "Jan 12 - Jan 28",
    daysWorked: ["m", "di", "w", "do", "vr"],
    status: "onLeave",
  },
  {
    id: "3",
    initials: "EO",
    name: "Elijah Oyin",
    totalHours: "1158.0hrs",
    overtimeHours: "38.0hrs",
    dateRange: "Jan 12 - Jan 20",
    daysWorked: ["m", "di", "w", "do", "vr"],
    status: "onLeave",
  },
  {
    id: "4",
    initials: "HG",
    name: "Haico De Gast",
    totalHours: "1158.0hrs",
    overtimeHours: "38.0hrs",
    dateRange: "Jan 2 - Jan 9",
    daysWorked: ["m", "di", "w", "do", "vr"],
    status: "onLeave",
  },
];
