import { Event } from "./types";

export const defaultDepartments = [
  "Behandelingkamer1",
  "Management",
  "Bijzonderheden-Verlof-Cursus-...",
  "Financien",
];

export const defaultEvents: Event[] = [
  {
    id: "1",
    department: "HG",
    title: "Surgery",
    startTime: "11:00",
    endTime: "13:00",
    staff: "Haico de Gast",
    color: "orange",
    column: 0,
    subColumn: 0,
    subColumnSpan: 1,
  },
  {
    id: "2",
    department: "DL",
    title: "Pijnspecialist",
    startTime: "11:00",
    endTime: "13:30",
    staff: "Diane Lane",
    color: "green",
    column: 0,
    subColumn: 1,
    subColumnSpan: 1,
  },
  {
    id: "3",
    department: "HG",
    title: "Pijnspecialist",
    startTime: "13:00",
    endTime: "15:00",
    staff: "Diane Lane",
    color: "yellow",
    column: 0,
    columnSpan: 2,
    subColumn: 2,
    subColumnSpan: 3,
  },
  {
    id: "4",
    department: "HG",
    title: "Pijnspecialist",
    startTime: "11:30",
    endTime: "13:30",
    staff: "Haico de Gast",
    color: "orange",
    column: 1,
    columnSpan: 2,
    subColumn: 2,
    subColumnSpan: 3,
  },
  {
    id: "5",
    department: "HG",
    title: "Pijnspecialist",
    startTime: "11:00",
    endTime: "15:30",
    staff: "Diane Lane",
    color: "green",
    column: 2,
    columnSpan: 2,
    subColumn: 2,
    subColumnSpan: 2,
  },
  {
    id: "6",
    department: "HG",
    title: "Pijnspecialist",
    startTime: "11:00",
    endTime: "13:00",
    staff: "Diane Lane",
    color: "yellow",
    column: 3,
    subColumn: 1,
    subColumnSpan: 1,
  },
];
